web:
  authentication:
    api_keys:
      soulmate_app:
        key: "soulmate-secret-api-key"
        role: readwrite
directories:
  downloads: /app/downloads

soulseek:
  username: "Salvatierra.pablom@gmail.com"
  password: "Tool1235813"
