tunnel: 1e0e7730-983e-4624-ab24-bc61ea6cea63
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: soulmate.lhommeduchili.xyz
    service: http://soulmate-backend:8000
  - service: http_status:404
